### Get all categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

### Get category by id
GET http://localhost:3000/api/categories/3
X-API-Key: RAHASIA

### Create category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
    "name": "Shoes"
}

### Update category
PUT http://localhost:3000/api/categories/3
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
    "name": ""
}

### Delete category
DELETE http://localhost:3000/api/categories/4
X-API-Key: RAHASIA
